[window]
opacity = 0.8

[font]
normal= {family ="Cozette", style = "Regular"}
size = 12

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "F", mods = "Control", action = "SearchForward" }
]
